// key identifies file name for image and is used in every href
// value

export const newsletter = [
  {
    key: 'krithi',
    email: 'ee20b038@iittp.ac.in',
    title: 'Krithi Shailya',
    link: 'https://www.linkedin.com/in/krithi-shailya-443758215',
    role: 'Editor-in-Chief',
  },
  {
    key: 'sneha',
    email: 'ch20b022@iittp.ac.in',
    title: 'Sneha M S',
    link: 'https://www.linkedin.com/in/snems/',
    role: 'Editor-in-Chief',
  },
  {
    key: 'anant',
    email: 'ee20b003@iittp.ac.in',
    title: 'Anant Tyagi',
    link: 'https://www.linkedin.com/in/anant-tyagi-80430a1ba',
    role: 'Art Editor Lead',
  },
  {
    key: 'sathyanarayann',
    email: 'ee20b046@iittp.ac.in',
    title: 'Sathyanarayann',
    link: 'mailto:ee20b046@iittp.ac.in',
    role: 'Editor',
  },
  {
    key: 'sachin',
    email: 'cs20b034@iittp.ac.in',
    title: 'Sachin Sahu',
    link: 'https://www.linkedin.com/in/sachin431/',
    role: 'Tech Team Lead',

  },
  {
    key: 'mohith',
    email: 'ch20b021@iittp.ac.in',
    title: 'Ram Mohith',
    link: 'https://www.linkedin.com/in/ram-mohith-223386218',
    role: 'Editor',
  },
  {
    key: 'chaitali',
    email: 'me20b053@iittp.ac.in',
    title: 'Chaitali Uday Karekar',
    link: 'https://www.linkedin.com/in/chaitali-karekar-829881230',
    role: 'Editor',
  },
  {
    key: 'battula',
    email: 'me21b045@iittp.ac.in',
    title: 'Sneha Battula',
    link: 'mailto:me21b045@iittp.ac.in',
    role: 'Editor',
  },
  {
    key: 'swathi',
    email: 'ce20b010@iittp.ac.in',
    title: 'Swathi',
    link: 'https://www.linkedin.com/in/swathi-gummadi-67826a226/',
    role: 'Editor',
  },
  {
    key: 'mathew',
    email: 'cs20b021@iittp.ac.in',
    title: 'Mathew KJ',
    link: 'https://www.linkedin.com/in/mathew-k-j-81957623b/',
    role: 'Tech Team',
  },
  {
    key: 'ganesh',
    email: 'cs20b026@iittp.ac.in',
    title: 'Ganesh Priyatham',
    link: 'https://www.linkedin.com/in/ganesh-priyatham-palivela-abb599229',
    role: 'Tech Team',
  },
  {
    key: 'saurabh',
    email: 'cs20b038@iittp.ac.in',
    title: 'Saurabh Kumar',
    link: 'https://www.linkedin.com/in/saurabh-kumar-089ab4241',
    role: 'Editor',
  },
  {
    key: 'keshav',
    email: 'cs21b027@iittp.ac.in',
    title: 'Keshav Kumar Manjhi',
    link: 'https://www.linkedin.com/in/keshav-manjhi-a8a2a321b',
    role: 'Art Editor',
  },
];
export const pastmembers = [
  {
    key: 'debeshee',
    title: 'Debeshee Das',
    tagLine1: '',
    tagLine2: '',
    role: 'Editor-in-Chief | 2022-23 , Editor | 2021-22',
    year: '2020-23',
    desc1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae diam euismod, aliquam elit vitae, ultricies ni',
    desc2:
      '',
    link: 'https://www.linkedin.com/in/debeshee-das/',
  },
  {
    key: 'noble',
    title: 'Noble Saji Mathews',
    tagLine1: '',
    tagLine2: '',
    role: 'Udaan\'s spine | Since inception, Tech team lead | 2020-23',
    year: '2020-23',
    desc1:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae diam euismod, aliquam elit vitae, ultricies ni',
    desc2:
      '',
    link: 'https://in.linkedin.com/in/noble-saji-mathews',
  },
  {
    key: 'sirish',
    title: 'Sirish',
    tagLine1: '',
    tagLine2: '',
    role: 'Tech team',
    year: '2022-23',
    desc1:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae diam euismod, aliquam elit vitae, ultricies ni',
    desc2:
      '',
    link: 'https://www.linkedin.com/in/sirish-sekhar-6896b51a7/',
  },
  {
    key: 'prabhat',
    title: 'Prabhat Reddy',
    tagLine1: 'AKA pace577. An institution and inspiration',
    tagLine2: 'The Prabotriarchy',
    role: 'Editor-in-chief',
    year: '2020-22',
    desc1: 'Team Udaan trailblazer and pacesetter.',
    desc2:
      'Designed,Organised and meticulously documented the workflow of Udaan',
    link: 'https://www.linkedin.com/in/prabhat-reddy-l-5b017062',
  },
  {
    key: 'shreyansh',
    title: 'Shreyansh Mehra',
    tagLine1: 'Founding Father',
    tagLine2: `The "lit" Sec, who started it all`,
    role: 'Editor-in-chief',
    year: '2020-22',
    desc1:
      'Team Udaan pioneer and visionary who brought to life the idea of a student-run institute magazine.',
    link: 'https://www.linkedin.com/in/shreyansh-mehra/',
  },
  {
    key: 'keerthana',
    title: 'Keerthana',
    tagLine1: 'Nss and Literary Enthusiast',
    role: 'Editor',
    year: '2021-22',
    desc1: 'Editor on the initial team of editors at Udaan',
    link: 'mailto:ee19b035@iittp.ac.in',
  },
  {
    key: 'preethi',
    title: 'Preethi Varsha',
    tagLine1: 'Editor',
    role: 'Editor',
    year: '2021-22',
    desc1:
      'Talents include drafting the perfect emails and perfecting any written material.',
    link: 'https://www.linkedin.com/in/preethi-varsha-70211b210',
  },
  {
    key: 'kranthi',
    title: 'Kranthi Sedamaki',
    tagLine1: 'Editor',
    role: 'Editor',
    year: '2022-23',
    desc1:
      'Kranthi was an editor at Udaan (2022-23) while pursuing a bachelor\'s in Computer Science and Engineering at IIT-T. He likes playing with the latest tech in his code playgrounds and loves working with data and AI! You can find him reading non-fiction books and playing Catan with his friends when he\'s not working.',
    link: 'https://www.linkedin.com/in/kranthisedamaki/',
  },
];

export const author_info = [
  {
    key: 'debeshee',
    title: 'Debeshee Das',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Debeshee is a ‘To-do’ List enthusiast and final year Computer Science and Engineering Undergraduate at IIT Tirupati, apart from being an Editor-in-Chief at Udaan. She’s always talking about paying attention to detail and how there isn’t enough time to do everything! She is also passionate about music, cake decorating, research, and (social) experiments (not necessarily in that order)!',
    desc2:
      '',
    link: '',
  },
  {
    key: 'aashrith',
    title: 'Aashrith Sai Madasu',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Aashrith is a final year undergraduate in Computer Science and Engineering at IIT Tirupati. He is passionate about technology, youtube, and making good connections with people. He loves learning from people about anything interesting and explores different things in technology and personal life.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'abhishek',
    title: 'Abhishek Bharadwaj',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Abhishek Bharadwaj is a machine learning and data science enthusiast and final year student from the Chemical Engineering branch. He is interested in cooking, music and gardening. He is also interested in researching any unknown thing he comes across. He is interested in sharing knowledge with others, so you will often see him explaining anything new he knows to his friends.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'amit',
    title: 'Amit Kesari',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Amit likes to experiment and explore a lot, covering a lot of ground, considering all the options and then moving ahead gradually understanding the topic/project and diving more deeply into it. He is never satisfied with the simple outcome and is always working on improvement so as to give his best. The same goes for disturbing and poking others and watching anime as well ;)',
    desc2:
      '',
    link: '',
  },
  {
    key: 'arunkumar',
    title: 'Arunkumar V',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Arunkumar is a third-year mechanical engineering student with a passion for robots and computer-aided design (CAD). He is enthusiastic about technology, entrepreneurial success stories, and music. He watches web series and explores new domains in his free time.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'bhargav',
    title: 'Nama Bhargav Sri Sai',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Bhargav is a final year Mechanical Undergraduate at IIT Tirupati. He is passionate about tennis, formula one and technology. He spends his free time binge-watching sitcoms and allots his weekends strictly for Formula One. If you run into any of his friends, ask them about his sense of humour, you will not be disappointed.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'gagan',
    title: 'Gagan Hegde',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Gagan is a computer science student doing his final year at IIT Tirupati. You will find him surfing the net for geopolitical and tech news if he’s not on his bicycle travelling ridiculous distances casually and gracefully, without breaking a sweat, like he’s just been taking a midnight stroll.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'noble',
    title: 'Noble Saji Mathews',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Noble. Just Noble is your go-to guy for everything tech. Apart from being the backbone of Udaan, he has 48 hours a day and makes magic happen with anything that has the slightest whiff of computers and technology. A guy who lives up to his name and beats the charts on the kindness scale, Noble is a fan of ‘sad non-love songs’ (which are shockingly hard to find), a Potterhead, and loves a quirky anime or a good mystery novel',
    desc2:
      '',
    link: '',
  },
  {
    key: 'pavan',
    title: 'Sreeram Pavan',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Seeram Pavan is a final year B.Tech civil engineering student (2019-2023 batch) from IIT Tirupati. He is passionate about being an entrepreneur and loves travelling. During his internship duration, he explored all the tourist places in Kerala every Sunday.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'pranav',
    title: 'Pranav Hari Panicker',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Pranav is a 4th Year B.Tech student in the EE department at IIT Tirupati who simply lives in the moment. He is an avid sports & movies fan with a sincere intention to "break bad" at some point in the future in some way or the other (which will probably never happen).',
    desc2:
      '',
    link: '',
  },
  {
    key: 'rishitha',
    title: 'T. Sai Rishitha',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Rishitha is highly interested in science and is a final year Mechanical Undergraduate at IIT Tirupati. She is passionate about Defense Technology, Automobiles and Aircrafts. She relaxes by involving in activities like cooking, photography and watching biopics. She sincerely works on polishing her skills for a better self.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'saket',
    title: 'Venkata Saket Ram Goteti',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Two things that excite Saket the most and provide solace during tough times are Science and Cricket. Any form of Cricket irrespective of the country or team that is playing. You can find him fascinated by random science videos over the internet, wondering how the human brain can do such incredible things. He is also often bingeing sitcoms on a loop, eternally.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'srikarah',
    title: 'Srikarah Volaity',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Srikarah, or Shriek as his friends like to call him, is a final year Civil & Environmental Engineering undergraduate at IIT Tirupati. He is probably the most lively yet lifeless person you will ever meet. Shriek finished his summer research internship at York University under the Mitacs program in the summer of 2022. Apart from being super interested in researching and trying to know ‘the answers’, he is passionate about basketball, emojis and exclamation points!!!',
    desc2:
      '',
    link: '',
  },
  {
    key: 'srinivas',
    title: 'Giridara Srinivaas',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'Srinivaas is a final year Chemical Engineering Undergraduate at IIT Tirupati and is one of the most sincere and dedicated but down-to-earth students you would come across. He has amazing general knowledge and will definitely take you on a deep dive into Indian History and Mythology if given the chance.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'venkatesa',
    title: 'J Venkatesa',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1:
      'J Venkatesa is a third-year electrical undergraduate interested in the field of electronics. He is passionate about technology, entrepreneurship and business. He is a travel enthusiast who loves playing chess and table tennis in his spare time.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'sneha',
    title: 'Sneha M S',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'An adventure seeker at heart, Sneha loves to explore both the real and fictional worlds. When she is not daydreaming about the Star Wars movie she would love to direct one day, you can find her procrastinating about anything and everything. Currently pursuing a degree in Mechanical Engineering at IIT Tirupati while also the Editor-in-Chief at Udaan, she is trying her best to make the best of her remaining college life',
    desc2: '',
    link: '',
  },
  {
    key: 'kranthi',
    title: 'Kranthi Sedamaki',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Kranthi is a senior at IIT Tirupati, pursuing a bachelor\'s in Computer Science and Engineering. He likes playing with the latest tech in his code playgrounds and loves working with data and AI! You can find him reading non-fiction books and playing Catan with his friends when he is not working.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'chaitali',
    title: 'Chaitali',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Chaitali is a pre final year Mechanical Engineering student at IIT Tirupati and one of the editors at Udaan. She enjoys editing stuff and making it more talkative and rhythmic. She might even add a rhyme or two if you’d like!  Her passions include music, literature, oration and music again!',
    desc2:
      '',
    link: '',
  },
  {
    key: 'udaan',
    title: 'Team Udaan',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'The team you know and love <3',
    desc2:
      '',
    link: '',
  },
  {
    key: 'priyansh',
    title: 'Priyansh',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Priyansh Sangule (IIMA 2023, IITT CSE 2020) is a tech and design enthusiast with eclectic interests.  With a particular penchant for creating open-source software and gaming, you’ll often find him appreciating beauty in the randomest of places. He occasionally publishes blogs and art through his digital garden: www.abstractxan.xyz.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'sathyanarayann',
    title: 'Sathyanarayann',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Sathyanarayann is a coffee addict  lover and an art enthusiast, who considers himself a walking shitpost. He can be found online on instagram at all ungodly hours of the day and night as he practically lives there. As a pre-final year student pursuing Electrical Engineering at IIT Tirupati, he is also a part of the Editors Team at Udaan, IITT’s very own student magazine. He enjoys bingeing on tv shows, art, deep philosophical conversations (preferably late night), art, obsessing over fictional characters in novels, poetry and, did I mention art?',
    desc2:
      '',
    link: '',
  },
  {
    key: 'battula',
    title: 'Sneha Battula',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'The younger Sneha of the IITT Udaan team, she is a generally small sized person with an even smaller attention span. She is pursuing Mechanical Engineering in her second year now at IIT Tirupati. Stepping into her shoes would mean walking through the pouring rain at 4 am, tiptoeing through shrubs to pick a flower, and stomping through a wasteland of a million daydreams. Call her on her phone and she will probably tell you she is in the middle of obsessively writing about the people she loves or precariously balancing on the edge of a huge wall for no reason but chaos.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'mathew',
    title: 'Mathew K J',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: '"Mathew K J" is the persona used by an automaton attempting to mimic human behaviour. It enjoys reading classic texts like "Lorem Ipsum", watching paint dry, debating the merits of anarcho-syndicalism and writing quirky things about itself in the third person.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'swathi',
    title: 'Swathi',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Swathi is a pre-final year Civil engineering student at IIT Tirupati. She is a self-observer who is keen enough to perceive not only herself but also things around her.  She is that one person with a very weird taste in food. In her free time, you can find her looping through the same playlist containing some 15 odd songs or watching some selected movies or web series on repeat. She has a problem giving closure to most of the stuff she does which includes this',
    desc2:
      '',
    link: '',
  },
  {
    key: 'krithi',
    title: 'Krithi Shailya',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Krithi is an extremely social and outgoing individual who goes by the tagline "I saw your text but forgot to reply". Apart from pursuing her pre- final year in Electrical engineering in IIT Tirupati, she is also constantly on the pursuit of life. You can find her looking homeless and vibing to the most random songs at any time in the day. She can promise to be your vibe friend and talk just about anything for as long as you want, but with a little bit of roasting, of course',
    desc2:
      '',
    link: '',
  },
  {
    key: 'mohith',
    title: 'Ram Mohith',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Mohith is a pre-final year chemical engineering student at IIT Tirupati who has a chain of thoughts running in his mind every time about his situation and manages to stay calm. He is curious about searching for new books to read and movies to watch and is equally lazy to start them. He likes reading random stuff from the web but forgets most of them in no time. He plays the same songs in a loop until, after a few days, they get replaced by new ones',
    desc2:
      '',
    link: '',
  },
  {
    key: 'keshav',
    title: 'Keshav Kumar Manjhi',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Keshav is a delightful busy bee, or perhaps more of a bee that tends to get stuck in too much honey and responsibilities. Hiding behind his genuinely sweet and friendly demeanour is a mischievous child with an obsession to be organised, and a sense of competition that burns gently in the back of his throat. Pursuing his second year of Computer Science and Engineering at IIT Tirupati, Keshav wades in a pool of the infinite tasks he assigns upon himself, all the many kittens he wishes to adopt in the near future, and the numerous skills he has hidden up his sleeve.',
    desc2:
      '',
    link: '',
  },
  {
    key: 'prabhat',
    title: 'Prabhat Reddy',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: "Prabhat is a hopelessly open-minded optimist who hopes that one day he'll have learned everything about everything. You can find him neck-deep in work or aimlessly goofing around; there is no in-between. If he’s not organising every minute of the existence of the universe into a computer-based journal, he’s probably bonding with a friendly stranger over Linux, Emacs, basketball, Linkin Park, anime or F.R.I.E.N.D.S. Currently pursuing his MS in Artificial Intelligence at C-MInDS, IIT Bombay, Prabhat was the ‘lit’ Secretary who breathed life into Udaan, the very magazine you’re reading right now!",
    desc2:
      '',
    link: 'https://www.linkedin.com/in/prabhat-reddy-l-5b017062',
  },
  {
    key: 'ME22S001',
    title: 'Umang Rastogi',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Umang Rastogi is an MS Research scholar in the Mechanical Engineering department at IIT Tirupati. He is also passionate about music, poetry, research and cricket. This poem is written in context with the father-daughter bond and shows love, gratitude, and appreciation.',
    desc2: '',
    link: '',
  },
  {
    key: 'MA20D001',
    title: 'Abhishek',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Abhishek Rajkumar, a poet at heart, likes to describe himself as a mere water droplet, moving with a society that will one day die and disappear. At present, he is a PhD scholar at the Department of Mathematics and Statistics, IIT Tirupati. Along with writing, he is a medium fast bowler and, not surprisingly, very fond of cricket.',
    desc2: '',
    link: '',
  },
  {
    key: 'EE19B022',
    title: 'K Sai Phani Charan',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: '',
    desc2: '',
    link: '',
  },
  {
    key: 'ME21B012',
    title: 'Bineet Barman',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'Bineet Barman - Bineet is a casual writer and a second year Mechanical Engineering undergraduate at IIT Tirupati, apart from being a guitarist for the institute\'s band. The following poem was composed impromptu for an Intra-IIT 2022 event with "considerable amount of naivety". He is also enthusiastic about art and instruments.',
    desc2: '',
    link: '',
  },
  {
    key: 'CS20B006',
    title: 'Bhukya Sanghu Sandeep',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'As a pre-final year Computer Science and Engineering undergraduate at IIT Tirupati, he has written his first story titled "First Contact," which takes readers on a deep dive into the narrative, allowing them to fully experience the story. In addition to writing, he is also passionate about music and movies.',
    desc2: '',
    link: '',
  },
  {
    key: 'CH21D005',
    title: 'Vipin Kumar Sharma',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: '',
    desc2: '',
    link: '',
  },
  {
    key: 'EE20B016',
    title: 'Iftekhar Ahmed',
    tagLine1: '',
    tagLine2: '',
    role: '',
    year: '',
    desc1: 'If you ask a friend of Iftekar’s to describe him, the first word that will helplessly tumble out of their mouth is ‘poet’. The soft-spoken poet, who radiates positive vibes and wields excellent oratory skills, Iftekhar, is currently pursuing an undergraduate degree in Electrical Engineering at IIT Tirupati. He is also a well-known badminton player who spends his spare time immersed in books and movies. ',
    desc2: '',
    link: '',
  },
];
