// key identifies file name for image and is used in every href
// value

export const newsletter = [
	{
		key: 'krithi',
		email: 'ee20b038@iittp.ac.in',
		title: 'Krithi Shailya',
		link: 'https://www.linkedin.com/in/krithi-shailya-443758215',
		role: 'Editor-in-Chief',
	},
	{
		key: 'sneha',
		email: 'me20b052@iittp.ac.in',
		title: 'Sneha M S',
		link: 'https://www.linkedin.com/in/snems/',
		role: 'Editor-in-Chief',
	},
	{
		key: 'anant',
		email: 'ee20b003@iittp.ac.in',
		title: 'Anant Tyagi',
		link: 'https://www.linkedin.com/in/anant-tyagi-80430a1ba',
		role: 'Art Editor Lead',
	},
	{
		key: 'sathyanarayann',
		email: 'ee20b046@iittp.ac.in',
		title: 'Sathyanarayann',
		link: 'https://www.linkedin.com/in/sathyanarayann-v-321b1b24',
		role: 'Editor',
	},
	{
		key: 'sachin',
		email: 'cs20b034@iittp.ac.in',
		title: 'Sachin Sahu',
		link: 'https://www.linkedin.com/in/sachin431/',
		role: 'Tech Team Lead',
	},
	{
		key: 'mohith',
		email: 'ch20b021@iittp.ac.in',
		title: 'Ram Mohith',
		link: 'https://www.linkedin.com/in/ram-mohith-223386218',
		role: 'Editor',
	},
	{
		key: 'chaitali',
		email: 'me20b053@iittp.ac.in',
		title: 'Chaitali Uday Karekar',
		link: 'https://www.linkedin.com/in/chaitali-karekar-829881230',
		role: 'Editor',
	},
	{
		key: 'battula',
		email: 'me21b045@iittp.ac.in',
		title: 'Sneha Battula',
		link: 'https://www.linkedin.com/in/sneha-battula-066b1122bn',
		role: 'Editor',
	},
	{
		key: 'swathi',
		email: 'ce20b010@iittp.ac.in',
		title: 'Swathi',
		link: 'https://www.linkedin.com/in/swathi-gummadi-67826a226/',
		role: 'Editor',
	},
	{
		key: 'saurabh',
		email: 'cs20b038@iittp.ac.in',
		title: 'Saurabh Kumar',
		link: 'https://www.linkedin.com/in/saurabh-kumar-089ab4241',
		role: 'Editor',
	},
	{
		key: 'akhil',
		email: 'me21b039@iittp.ac.in',
		title: 'Akhil Krishnan',
		link: 'https://www.linkedin.com/in/akhil-krishnan-bb113426b',
		role: 'Editor',
	},
	{
		key: 'ME21B012',
		email: 'me21b012@iittp.ac.in',
		title: 'Bineet Barman',
		link: 'https://www.linkedin.com/in/bineet-barman-0a9563242',
		role: 'Editor',
	},
	{
		key: 'mathew',
		email: 'cs20b021@iittp.ac.in',
		title: 'Mathew KJ',
		link: 'https://www.linkedin.com/in/mathew-k-j-81957623b/',
		role: 'Tech Team',
	},
	{
		key: 'ganesh',
		email: 'cs20b026@iittp.ac.in',
		title: 'Ganesh Priyatham',
		link: 'https://www.linkedin.com/in/ganesh-priyatham-palivela-abb599229',
		role: 'Tech Team',
	},

	{
		key: 'keshav',
		email: 'cs21b027@iittp.ac.in',
		title: 'Keshav Kumar Manjhi',
		link: 'https://www.linkedin.com/in/keshav-manjhi-a8a2a321b',
		role: 'Art Editor',
	},
	{
		key: 'tarun',
		email: 'me21b051@iittp.ac.in',
		title: 'Tarun J Palani',
		link: 'https://www.linkedin.com/in/tarun-j-palani-1033b3284',
		role: 'Art Editor',
	},
	{
		key: 'siddhartha',
		email: 'cs20b040@iittp.ac.in',
		title: 'Siddhartha G',
		link: 'https://www.linkedin.com/in/siddharthag22/',
		role: 'Tech Team',
	},
	{
		key: 'me21b006',
		email: 'me21b006@iittp.ac.in',
		title: 'Ansh Anand',
		link: 'https://www.linkedin.com/in/anshanandp',
		role: 'Tech Team',
	},
];
export const pastmembers = [
	{
		key: 'debeshee',
		title: 'Debeshee Das',
		tagLine1: 'Udaan Blithe',
		tagLine2: '',
		role: 'Editor-in-Chief | 2022-23 , Editor | 2021-22',
		year: '',
		desc1: 'Being a part of the editorial team in her initial years, Debeshee took over the Chief Editor role for the year 2022-23 and carried Udaan to greater heights with initiatives like the Podcast, new editions, and many more. Known for her “how is she so talented” vibe, she managed to give Udaan her own little touch and is often found furiously documenting meetings or laughing at quite literally everything.',
		desc2: '',
		link: 'https://www.linkedin.com/in/debeshee-das/',
	},
	{
		key: 'noble',
		title: 'Noble Saji Mathews',
		tagLine1: "Udaan's spine",
		tagLine2: 'The Actual Fourth Maraurder',
		role: ' Tech Team lead ',
		year: '2020-23',
		desc1: 'The unparalleled technical lead who gave the writers a place to write, the audience a place to read, and Udaan a home. This extremely noble (get it?) Udaan elder considers sleep a formality and can frequently be spotted changing Discord names during voice calls.  ',
		desc2: '',
		link: 'https://in.linkedin.com/in/noble-saji-mathews',
	},
	{
		key: 'sirish',
		title: 'Sirish',
		tagLine1: 'Tech Team',
		tagLine2: 'Interviewer',
		role: 'Tech team',
		year: '2022-23',
		desc1: 'As a part of the tech team, Sirish blended right in with Udaan and helped explore various technical aspects of an online magazine He is an extremely fun person to work with and always has the perfect level of quirkiness embedded in his reply. ',
		desc2: '',
		link: 'https://www.linkedin.com/in/sirish-sekhar-6896b51a7/',
	},
	{
		key: 'prabhat',
		title: 'Prabhat Reddy',
		tagLine1: 'AKA pace577. An institution and inspiration',
		tagLine2: 'The Prabotriarchy',
		role: 'Editor-in-chief',
		year: '2020-22',
		desc1: 'Team Udaan trailblazer and pacesetter.',
		desc2: 'Designed, organised and meticulously documented the workflow of Udaan',
		link: 'https://www.linkedin.com/in/prabhat-reddy-l-5b017062',
	},
	{
		key: 'shreyansh',
		title: 'Shreyansh Mehra',
		tagLine1: 'Founding Father',
		tagLine2: 'The "lit" Sec, who started it all',
		role: 'Editor-in-chief',
		year: '2020-22',
		desc1: 'Team Udaan pioneer and visionary who brought to life the idea of a student-run institute magazine.',
		link: 'https://www.linkedin.com/in/shreyansh-mehra/',
	},
	{
		key: 'keerthana',
		title: 'Keerthana',
		tagLine1: 'Nss and Literary Enthusiast',
		role: 'Editor',
		year: '2021-22',
		desc1: 'Editor on the initial team of editors at Udaan',
		link: 'mailto:ee19b035@iittp.ac.in',
	},
	{
		key: 'preethi',
		title: 'Preethi Varsha',
		tagLine1: 'Editor',
		role: 'Editor',
		year: '2021-22',
		desc1: 'Talents include drafting the perfect emails and perfecting any written material.',
		link: 'https://www.linkedin.com/in/preethi-varsha-70211b210',
	},
	{
		key: 'kranthi',
		title: 'Kranthi Sedamaki',
		tagLine1: 'Editor',
		role: 'Editor',
		year: '2022-23',
		desc1: "Kranthi was an editor at Udaan (2022-23) while pursuing a bachelor's in Computer Science and Engineering at IIT-T. He likes playing with the latest tech in his code playgrounds and loves working with data and AI! You can find him reading non-fiction books and playing Catan with his friends when he's not working.",
		link: 'https://www.linkedin.com/in/kranthisedamaki/',
	},
];

export const author_info = [
	{
		key: 'debeshee',
		title: 'Debeshee Das',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Debeshee is a ‘To-do’ List enthusiast and final year Computer Science and Engineering Undergraduate at IIT Tirupati, apart from being an Editor-in-Chief at Udaan. She’s always talking about paying attention to detail and how there isn’t enough time to do everything! She is also passionate about music, cake decorating, research, and (social) experiments (not necessarily in that order)!',
		desc2: '',
		link: '',
	},
	{
		key: 'aashrith',
		title: 'Aashrith Sai Madasu',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Aashrith is a final year undergraduate in Computer Science and Engineering at IIT Tirupati. He is passionate about technology, youtube, and making good connections with people. He loves learning from people about anything interesting and explores different things in technology and personal life.',
		desc2: '',
		link: '',
	},
	{
		key: 'abhishek',
		title: 'Abhishek Bharadwaj',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Abhishek Bharadwaj is a machine learning and data science enthusiast and final year student from the Chemical Engineering branch. He is interested in cooking, music and gardening. He is also interested in researching any unknown thing he comes across. He is interested in sharing knowledge with others, so you will often see him explaining anything new he knows to his friends.',
		desc2: '',
		link: '',
	},
	{
		key: 'amit',
		title: 'Amit Kesari',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Amit likes to experiment and explore a lot, covering a lot of ground, considering all the options and then moving ahead gradually understanding the topic/project and diving more deeply into it. He is never satisfied with the simple outcome and is always working on improvement so as to give his best. The same goes for disturbing and poking others and watching anime as well ;)',
		desc2: '',
		link: '',
	},
	{
		key: 'arunkumar',
		title: 'Arunkumar V',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Arunkumar is a fourth-year mechanical undergraduate who is deeply passionate about design and optimization. His enthusiasm extends to tech talks, entrepreneurship, and music, which he considers his core interests. He likes multitasking and also strives to get the best out of himself. When he\'s not hustling, you\'ll find him chilling out with his friends, listening to music, and binge-watching anime. Get to know him well, and you\'ll discover a super-fun hangout buddy too!',
		desc2: '',
		link: '',
	},
	{
		key: 'bhargav',
		title: 'Nama Bhargav Sri Sai',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Bhargav is a final year Mechanical Undergraduate at IIT Tirupati. He is passionate about tennis, formula one and technology. He spends his free time binge-watching sitcoms and allots his weekends strictly for Formula One. If you run into any of his friends, ask them about his sense of humour, you will not be disappointed.',
		desc2: '',
		link: '',
	},
	{
		key: 'gagan',
		title: 'Gagan Hegde',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Gagan is a computer science student doing his final year at IIT Tirupati. You will find him surfing the net for geopolitical and tech news if he’s not on his bicycle travelling ridiculous distances casually and gracefully, without breaking a sweat, like he’s just been taking a midnight stroll.',
		desc2: '',
		link: '',
	},
	{
		key: 'noble',
		title: 'Noble Saji Mathews',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Noble. Just Noble is your go-to guy for everything tech. Apart from being the backbone of Udaan, he has 48 hours a day and makes magic happen with anything that has the slightest whiff of computers and technology. A guy who lives up to his name and beats the charts on the kindness scale, Noble is a fan of ‘sad non-love songs’ (which are shockingly hard to find), a Potterhead, and loves a quirky anime or a good mystery novel',
		desc2: '',
		link: '',
	},
	{
		key: 'pavan',
		title: 'Sreeram Pavan',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Seeram Pavan is a final year B.Tech civil engineering student (2019-2023 batch) from IIT Tirupati. He is passionate about being an entrepreneur and loves travelling. During his internship duration, he explored all the tourist places in Kerala every Sunday.',
		desc2: '',
		link: '',
	},
	{
		key: 'pranav',
		title: 'Pranav Hari Panicker',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Pranav is a 4th Year B.Tech student in the EE department at IIT Tirupati who simply lives in the moment. He is an avid sports & movies fan with a sincere intention to "break bad" at some point in the future in some way or the other (which will probably never happen).',
		desc2: '',
		link: '',
	},
	{
		key: 'rishitha',
		title: 'T. Sai Rishitha',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Rishitha is highly interested in science and is a final year Mechanical Undergraduate at IIT Tirupati. She is passionate about Defense Technology, Automobiles and Aircrafts. She relaxes by involving in activities like cooking, photography and watching biopics. She sincerely works on polishing her skills for a better self.',
		desc2: '',
		link: '',
	},
	{
		key: 'saket',
		title: 'Venkata Saket Ram Goteti',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Two things that excite Saket the most and provide solace during tough times are Science and Cricket. Any form of Cricket irrespective of the country or team that is playing. You can find him fascinated by random science videos over the internet, wondering how the human brain can do such incredible things. He is also often bingeing sitcoms on a loop, eternally.',
		desc2: '',
		link: '',
	},
	{
		key: 'srikarah',
		title: 'Srikarah Volaity',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Srikarah, or Shriek as his friends like to call him, is a final year Civil & Environmental Engineering undergraduate at IIT Tirupati. He is probably the most lively yet lifeless person you will ever meet. Shriek finished his summer research internship at York University under the Mitacs program in the summer of 2022. Apart from being super interested in researching and trying to know ‘the answers’, he is passionate about basketball, emojis and exclamation points!!!',
		desc2: '',
		link: '',
	},
	{
		key: 'srinivas',
		title: 'Giridara Srinivaas',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Srinivaas is a final year Chemical Engineering Undergraduate at IIT Tirupati and is one of the most sincere and dedicated but down-to-earth students you would come across. He has amazing general knowledge and will definitely take you on a deep dive into Indian History and Mythology if given the chance.',
		desc2: '',
		link: '',
	},
	{
		key: 'venkatesa',
		title: 'J Venkatesa',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'J Venkatesa is a third-year electrical undergraduate interested in the field of electronics. He is passionate about technology, entrepreneurship and business. He is a travel enthusiast who loves playing chess and table tennis in his spare time.',
		desc2: '',
		link: '',
	},
	{
		key: 'sneha',
		title: 'Sneha M S',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'An adventure seeker at heart, Sneha loves to explore both the real and fictional worlds. When she is not daydreaming about the Star Wars movie she would love to direct one day, you can find her procrastinating about anything and everything. Currently pursuing a degree in Mechanical Engineering at IIT Tirupati while also the Editor-in-Chief at Udaan, she is trying her best to make the best of her remaining college life',
		desc2: '',
		link: '',
	},
	{
		key: 'kranthi',
		title: 'Kranthi Sedamaki',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: "Kranthi is a senior at IIT Tirupati, pursuing a bachelor's in Computer Science and Engineering. He likes playing with the latest tech in his code playgrounds and loves working with data and AI! You can find him reading non-fiction books and playing Catan with his friends when he is not working.",
		desc2: '',
		link: '',
	},
	{
		key: 'chaitali',
		title: 'Chaitali Karekar',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Chaitali is a final year Mechanical Engineering student at IIT Tirupati and one of the editors at Udaan. She enjoys editing stuff and making it more talkative and rhythmic. She might even add a rhyme or two if you’d like!  Her passions include music, literature, oration and music again!',
		desc2: '',
		link: '',
	},
	{
		key: 'udaan',
		title: 'Team Udaan',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'The team you know and love <3',
		desc2: '',
		link: '',
	},
	{
		key: 'priyansh',
		title: 'Priyansh',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Priyansh Sangule (IIMA 2023, IITT CSE 2020) is a tech and design enthusiast with eclectic interests.  With a particular penchant for creating open-source software and gaming, you’ll often find him appreciating beauty in the randomest of places. He occasionally publishes blogs and art through his digital garden: www.abstractxan.xyz.',
		desc2: '',
		link: '',
	},
	{
		key: 'sathyanarayann',
		title: 'Sathyanarayann',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Sathyanarayann is a coffee addict  lover and an art enthusiast, who considers himself a walking shitpost. He can be found online on instagram at all ungodly hours of the day and night as he practically lives there. As a final year student pursuing Electrical Engineering at IIT Tirupati, he is also a part of the Editors Team at Udaan, IITT’s very own student magazine. He enjoys bingeing on tv shows, art, deep philosophical conversations (preferably late night), art, obsessing over fictional characters in novels, poetry and, did I mention art?',
		desc2: '',
		link: 'www.linkedin.com/in/sathyanarayann-v-321b1b24',
	},
	{
		key: 'battula',
		title: 'Sneha Battula',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'The younger Sneha of the IITT Udaan team, she is a generally small sized person with an even smaller attention span. She is pursuing Mechanical Engineering in her third year now at IIT Tirupati. Stepping into her shoes would mean walking through the pouring rain at 4 am, tiptoeing through shrubs to pick a flower, and stomping through a wasteland of a million daydreams. Call her on her phone and she will probably tell you she is in the middle of obsessively writing about the people she loves or precariously balancing on the edge of a huge wall for no reason but chaos.',
		desc2: '',
		link: 'https://www.linkedin.com/in/sneha-battula-066b1122b',
	},
	{
		key: 'mathew',
		title: 'Mathew KJ',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: '"Mathew KJ" is the persona used by an automaton attempting to mimic human behaviour. It enjoys reading classic texts like "Lorem Ipsum", watching paint dry, debating the merits of anarcho-syndicalism and writing quirky things about itself in the third person.',
		desc2: '',
		link: '',
	},
	{
		key: 'swathi',
		title: 'Swathi',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Swathi is a final year Civil engineering student at IIT Tirupati. She is a self-observer who is keen enough to perceive not only herself but also things around her.  She is that one person with a very weird taste in food. In her free time, you can find her looping through the same playlist containing some 15 odd songs or watching some selected movies or web series on repeat. She has a problem giving closure to most of the stuff she does which includes this',
		desc2: '',
		link: '',
	},
	{
		key: 'krithi',
		title: 'Krithi Shailya',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Krithi is an extremely social and outgoing individual who goes by the tagline "I saw your text but forgot to reply". Apart from pursuing her final year in Electrical engineering at IIT Tirupati whilst also being the Editor-in-Chief at Udaan, she is also constantly on the pursuit of life. You can find her looking homeless and vibing to the most random songs at any time in the day. She can promise to be your vibe friend and talk just about anything for as long as you want, but with a little bit of roasting, of course.',
		desc2: '',
		link: '',
	},
	{
		key: 'mohith',
		title: 'Ram Mohith',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Mohith is a final year chemical engineering student at IIT Tirupati who has a chain of thoughts running in his mind every time about his situation and manages to stay calm. He is curious about searching for new books to read and movies to watch and is equally lazy to start them. He likes reading random stuff from the web but forgets most of them in no time. He plays the same songs in a loop until, after a few days, they get replaced by new ones',
		desc2: '',
		link: '',
	},
	{
		key: 'keshav',
		title: 'Keshav Kumar Manjhi',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Keshav is a delightful busy bee, or perhaps more of a bee that tends to get stuck in too much honey and responsibilities. Hiding behind his genuinely sweet and friendly demeanour is a mischievous child with an obsession to be organised, and a sense of competition that burns gently in the back of his throat. Pursuing his third year of Computer Science and Engineering at IIT Tirupati, Keshav wades in a pool of the infinite tasks he assigns upon himself, all the many kittens he wishes to adopt in the near future, and the numerous skills he has hidden up his sleeve.',
		desc2: '',
		link: '',
	},
	{
		key: 'prabhat',
		title: 'Prabhat Reddy',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: "Prabhat is a hopelessly open-minded optimist who hopes that one day he'll have learned everything about everything. You can find him neck-deep in work or aimlessly goofing around; there is no in-between. If he’s not organising every minute of the existence of the universe into a computer-based journal, he’s probably bonding with a friendly stranger over Linux, Emacs, basketball, Linkin Park, anime or F.R.I.E.N.D.S. Currently pursuing his MS in Artificial Intelligence at C-MInDS, IIT Bombay, Prabhat was the ‘lit’ Secretary who breathed life into Udaan, the very magazine you’re reading right now!",
		desc2: '',
		link: 'https://www.linkedin.com/in/prabhat-reddy-l-5b017062',
	},
	{
		key: 'ME22S001',
		title: 'Umang Rastogi',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Umang Rastogi is an MS Research scholar in the Mechanical Engineering department at IIT Tirupati. He is also passionate about music, poetry, research and cricket. This poem is written in context with the father-daughter bond and shows love, gratitude, and appreciation.',
		desc2: '',
		link: '',
	},
	{
		key: 'MA20D001',
		title: 'Abhishek',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Abhishek Rajkumar, a poet at heart, likes to describe himself as a mere water droplet, moving with a society that will one day die and disappear. At present, he is a PhD scholar at the Department of Mathematics and Statistics, IIT Tirupati. Along with writing, he is a medium fast bowler and, not surprisingly, very fond of cricket.',
		desc2: '',
		link: '',
	},
	{
		key: 'EE19B022',
		title: 'K Sai Phani Charan',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: '',
		desc2: '',
		link: '',
	},
	{
		key: 'ME21B012',
		title: 'Bineet Barman',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Bineet is a lethargic individual, phasing through his Mechanical Engineering degree. Though with a general interest in all arts, he focuses primarily on playing guitar. For some amounts, he also enjoys reading, writing, and editing, regardless of his understanding. His current hope is to keep up with his peers and become an adept adult by the end of his college education. He will probably need an MTech degree too. And a PhD.',
		desc2: '',
		link: 'https://www.linkedin.com/in/bineet-barman-0a9563242',
	},
	{
		key: 'CS20B006',
		title: 'Bhukya Sanghu Sandeep',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'As a pre-final year Computer Science and Engineering undergraduate at IIT Tirupati, he has written his first story titled "First Contact," which takes readers on a deep dive into the narrative, allowing them to fully experience the story. In addition to writing, he is also passionate about music and movies.',
		desc2: '',
		link: '',
	},
	{
		key: 'CH21D005',
		title: 'Vipin Kumar Sharma',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: '',
		desc2: '',
		link: '',
	},
	{
		key: 'EE20B016',
		title: 'Iftekhar Ahmed',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'If you ask a friend of Iftekar’s to describe him, the first word that will helplessly tumble out of their mouth is ‘poet’. The soft-spoken poet, who radiates positive vibes and wields excellent oratory skills, Iftekhar, is currently pursuing an undergraduate degree in Electrical Engineering at IIT Tirupati. He is also a well-known badminton player who spends his spare time immersed in books and movies. ',
		desc2: '',
		link: '',
	},
	{
		key: 'me21b006',
		title: 'Ansh Anand',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Ansh, a perpetually curious soul, thrives on the thrill of exploring and creating the unknown. With an insatiable appetite for knowledge, Ansh can often be found diving deep into diverse topics, ranging from technology and science to philosophy and politics but when it comes to his own academic course, he may occasionally resemble a lost traveler in the backrooms.',
		desc2: '',
		link: 'https://www.linkedin.com/in/anshanandp',
	},
	{
		key: 'akhil',
		title: 'Akhil Krishnan',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Akhil is your average "I suck at this life stuff, but I love it" human. Considered by few to be a hopeless romantic, he is of the opinion that soft music can reach into your heart and simply shatter it. You can find him staring at every passing pretty car and if you can\'t find him, chances are he\'s asleep from all the nightowlness. He is also a huge video game fangirl. Currently pursuing his dream degree in Mechanical Engineering, he hopes to swim through life and make it out in one piece, him and the indecisiveness that never leaves him.',
		link: 'https://www.linkedin.com/in/akhil-krishnan-bb113426b',
	},
	{
		key: 'rudransh',
		title: 'Rudransh Pujari',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Rudransh, a B.Tech student pursuing Mechanical Engineering. From his infamous "chidiya ka ghosla" hairstyle, he has transformed into a more presentable person to represent the student community. With an undying love for basketball and tennis, he never fails to catch the excitement of  Grand Slams and NBA playoffs. Alongside his passion for sports, Rudransh is an occasional writer and a devoted documentary enthusiast.',
		link: '',
	},
	{
		key: 'neerav',
		title: 'Neerav Sreekumar',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Neerav actually means silence in Sanskrit, and it may be fair enough to call him a taciturn. A sophomore pursuing a BTech in Chemical Engineering at IIT Tirupati, he is known for being a committed lover, but the only twist being that his soulmate is football. Apart from being a Bayern Munich fanatic, he enjoys Hollywood, novels, chess and being a meat foodie. His weakness? Not being run by an open source algorithm.',
		link: '',
	},
	{
		key: 'rajat',
		title: 'Rajat Pratap',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Rajat Pratap, a poet of ethereal grace, intertwines the splendour of humanity with the boundless majesty of nature, enchanting hearts through his poetic mastery. With each verse, he unveils the profound unity between individuals and the natural world, casting spells that transcend the ordinary. Beyond his literary prowess, He finds solace in the melodies of song, the strategic dance of chess, and the spirited rivalry of Badminton. A wanderer at heart, he seeks inspiration by exploring the hidden corners of the world, breathing life into his poetry with the essence of his journeys. ',
		desc2: '',
		link: '',
	},
	{
		key: 'sushant',
		title: 'Sushant Nasare',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Sushant is currently in his final year pursuing a B.Tech degree in Electrical Engineering at IIT Tirupati. He possesses a strong passion for Machine Learning and Computer Vision and is currently navigating the complexities of life. He is particularly fascinated by deep learning, continuous learning, adaptation and resilience. During his free moments, he enjoys watching movies or series, listening to music or hanging out with friends. The choice depends on his mood. Additionally, Sushant holds the position of placement coordinator in the college.',
		desc2: '',
		link: '',
	},
	{
		key: 'ishaan',
		title: 'Ishaan Kulkarni',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Ishaan is a final year Computer Science and Engineering student from IIT Tirupati. He is currently working on creating ML models for object detection given a very small amount of data. Apart from coding his way through life, he is a passionate cook, a connoisseur of Mumbai street food and believes in humouring his way through day to day life. He loves motivating his friends and solving abstract problems. His pastimes include  watching movies and listening to music in his mother tongue - Marathi. On a windy evening, you may find him at his favourite spot on campus; the railings near the lake.',
		desc2: '',
		link: '',
	},
	{
		key: 'sumukh',
		title: 'Sumukh Porwal',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Sumukh is a 4th year mechanical engineering undergraduate at IIT Tirupati. He is passionate about research in the field of robotics and control.',
		desc2: '',
		link: '',
	},
	{
		key: 'anant',
		title: 'Anant Tyagi',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Anant is a 4th year half CS half EE student who has given up on life a long, long while ago. He\'s usually found delightfully eating the last sweet in the box or taking pictures in some random alley, couple of the very few things that give him peace. Despite being good at many trades, his average day goes by in bed because he\'ll put effort into something only if it\'s more exciting than sleep.',
		desc2: '',
		link: '',
	},
	{
		key: 'sachin',
		title: 'Sachin Sahu',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Sachin is a tech enthusiast and a final-year Computer Science and Engineering student at IIT Tirupati. He also leads the tech team at Udaan. In this article, he recounts his delightful summer in the tech-centric city of Hyderabad, sharing his newfound love for it.  He is passionate about coding, hackathons, and problem-solving. While he might not be the most talkative person, he\'s a loyal friend who always makes sure everyone he talks to feels respected :)',
		desc2: '',
		link: '',
	},
	{
		key: 'vikas',
		title: 'Sai Vikas',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Sai is a final-year Mechanical Engineering Undergraduate at IIT Tirupati who loves to talk to people and have fun with friends. He definitely does not like reading books, novels, fiction or anything that requires rigorous wordplay (sadly, he has no such good habits😜). He likes to read case studies on business and geo-politics. He likes to keep things simple and easy (he admits he is very lazy and always tries to find shortcuts). He used to play a lot of sports, but he had to stop them to be responsible for at least one phase of his life (he says he plays well, though, but we are not sure if we should believe him 😂). He hopes you enjoy his blog and don’t judge him too harshly for any peccadilloes in his writing because he is not used to writing any blogs.',
		desc2: '',
		link: '',
	},
	{
		key: 'srihitha',
		title: 'Srihitha',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Srihitha is an extremely introverted final year electrical engineering student at IIT Tirupati. During her free time she can be found either watching friends or hanging out with her tiny friends circle. She is that type of person who sees sports complex as exam center. She is an earlybird and cannot be contacted by anyone after 11pm.',
		desc2: '',
		link: '',
	},
	{
		key: 'kanishk',
		title: 'Kanishk Kumar',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: ' Kanishk is a space enthusiast and 4th year Chemical Engineering Undergraduate at IIT Tirupati, as well as a member of the IIT Tirupati Technical Newsletter Team. His internship was at BluJ Aero, a Hyderabad-based aviation start-up. He also enjoys playing football and going to the gym, as well as experimenting and exploring new things.',
		desc2: '',
		link: '',
	},
	{
		key: 'samhitha',
		title: 'Samhitha',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Samhitha is a final year Electrical student interested in watching every sport but not playing. She is a positive spirited ambivert who can crack jokes on anyone and anytime. She is that kind of a person who has a different take on life which gets reflected in her taste of movies and series. Apart from studying, her hobbies include roasting her friends.',
		desc2: '',
		link: '',
	},
	{
		key: 'saicharan',
		title: 'Sai Charan',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Sai Charan, a senior Mechanical Engineering student at IIT Tirupati, possesses a strong penchant for keenly observing his surroundings. He frequently engages in introspective conversations with himself, reflecting his thoughtful nature. During his leisure hours, you can often find him either indulging in peaceful slumber or striking up conversations with new acquaintances. Furthermore, he derives great joy from repeatedly humming a particular song. Sai Charan is fully dedicated to pursuing core engineering roles, setting himself apart from the majority of his friends who have ventured into non-core fields, a fact that imbues him with a sense of uniqueness and accomplishment.',
		desc2: '',
		link: '',
	},
	{
		key: 'anush',
		title: 'Anush Mangal',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Anush is a final year Computer Science and Engineering student at IIT Tirupati. He has varied interests and is particularly curious about natural sciences and the mysteries they unravel. Sometimes he gets obsessed with astronomy, sometimes poker, and at times, movies, history, chemistry, core computer sciences, or just watching brain and heart dissection videos on YouTube 🤷‍♂️.  To sum it all, he is just a curious fellow who does not know what to do, what might grab his attention, and what might satisfy his curiosity.',
		desc2: '',
		link: '',
	},
	{
		key: 'shivendra',
		title: 'Shivendra Kumar Gupta',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Shivendra, is a final year Civil & Environmental Engineering undergraduate at IIT Tirupati. He is probably one of the most vibrant, communicative, serene, and emotionally expressive individuals you\'ll ever meet. Shivendra finished his summer research internship at Western University under the Mitacs program in the summer of 2023. In addition to his strong enthusiasm for exploring and seeking knowledge, he has a deep passion for listening to stories and is eager to learn badminton.',
		desc2: '',
		link: '',
	},
	{
		key: 'sunandan',
		title: 'Sunandan Gad',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Sunandan is a guy generally introvert, but loves talking about random deep issues of life, if someone strikes up a convo with him. Even a couple of hours aren’t enough then. Focused unnecessarily too much on academics, he finds time to listen to absolute opposite music genres in a span of an hour, from a sad melody to a full-blown F-bomb filled Eminem, you name it. He’s now in the final year of his B.Tech. in Chemical Engineering, and is surprised of two things: How come I develop interest in CH this late, and how come we are already a step out of this college? Still, his one strange habit is to show up some 10-odd minutes early to some of the absolute soul-sucking classes.',
		desc2: '',
		link: '',
	},
	{
		key: 'yamini',
		title: 'Yamini Shree',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Yamini is a perpetually loud computer science student who is almost always found outdoors. When she isn\'t breaking her back with CS assignments or coding, you can find her fooling around and being silly with the people she loves. ',
		desc2: '',
		link: '',
	},
	{
		key: 'sriharipriya',
		title: 'Sriharipriya',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Sriharipriya is a final year Civil and Environmental Engineering Undergraduate at IIT Tirupati. During her free time, you can find her studying or reading some random comics. Her methods of stress relief include playing sports and cooking. In this article, you\'ll delve about planning of activities involved in the construction of Chennai Metro Rail Elevated Viaduct Project which she explored as a part of her summer internship.',
		desc2: '',
		link: '',
	},
	{
		key: 'anvay',
		title: 'Anvay Joshi',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Anvay is a first year undergrad pursuing Electrical Engineering at IIT Tirupati. Apart from constantly overthinking and reconsidering life choices, Anvay is a fan of Table Tennis, Guitar, Coding and whatnot. He loves making friends and goes out of the way to make himself look approachable. Poetry is his tool to express his emotions  and thoughts, often on impulse.',
		desc2: '',
		link: '',
	},
	{
		key: 'shreyas',
		title: 'Shreyas Suresh',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Shreyas Suresh is a final-year mech student at IIT-Tirupati. Thank you.',
		desc2: '',
		link: '',
	},
	{
		key: 'dhanesh',
		title: 'Dhanesh',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Dhanesh is a final year student at IIT Tirupati. He is a passionate individual who finds beauty in both the physics of nature and the complexities of the human mind. He enjoys the art of dance, singing, drawing, coding and hanging with friends physically. His simple and polite nature helps him to connect with people and explore the world through his unique perspective.',
		desc2: '',
		link: '',
	},
	{
		key: 'jaswanth',
		title: 'Jaswanth',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Jaswanth is a firm believer that anime worlds are real somewhere in the multi-verse. He can\'t help but feel a bit disappointed that he\'s stuck in this "boring" universe, eagerly waiting for the day he might wake up in one of those fantastical realms. Currently in his final year of B.Tech in the Electrical department, he\'s always up for a chat about anime and Marvel, making it easy to befriend him if you share his passions.',
		desc2: '',
		link: '',
	},
	{
		key: 'gayathrip',
		title: 'Gayathri',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Gayathri is a lively and joyful girl who finds immense delight in exploring the world of Korean dramas as a dedicated aficionado. Alongside her passion for Kdramas, she is an ardent fan of BTS and enjoys immersing herself in their music, as well as exploring other genres. With a vibrant and adventurous spirit, Gayathri loves spending quality time with her friends, cherishing the laughter and camaraderie they share. Always seeking new experiences, she eagerly embraces opportunities to go out and create unforgettable memories.',
		desc2: '',
		link: '',
	},
	{
		key: 'rahul',
		title: 'Rahul',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Rahul is a final-year Civil and Environmental Engineering undergraduate at IIT Tirupati. He\'s enthusiastic about research related to sustainability and energy conservation studies. He\'s sincerely trying to enhance his research and problem-solving skills. In his free time, he enjoys playing badminton and watching cricket.',
		desc2: '',
		link: '',
	},
	{
		key: 'naveen',
		title: 'Naveen',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Naveen is an ambitious and fun-loving student, currently pursuing an undergraduate degree in civil engineering at IIT Tirupati. He is passionate about movies, music and research works. Apart from classrooms and laboratories, you can find him chatting with his friends in the cafeteria, trying to solve non-existent problems.',
		desc2: '',
		link: '',
	},
	{
		key: 'akshat',
		title: 'Akshat Seth',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Akshat is a loquacious being to whom you could talk about any random crazy stuff unless he\'s not diving into his musical ocean via a pair of earpods. You can find him roaming around at any hour at the most unexpected places, especially when it\'s raining, wondering about the decision to pursue his degree in Civil and Environmental Engineering. Eager to learn what life offers, he hopes to complete his pre-final year swiftly.',
		desc2: '',
		link: '',
	},
	{
		key: 'yuv',
		title: 'Yuv Raj',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Yuv Raj, a second-year student, hails from the picturesque hills of Himachal Pradesh. Beyond the confines of textbooks and circuits, he finds joy and relaxation in rhythmic exchanges of table tennis battles and has a deep connection with the world of music. Occasionally, he indulges his creative side by penning down poems that reflect the depth of his emotions and thoughts. His belief in Edward Bulwer-Lytton\'s famous saying, "Pen is mightier than the sword," resonates in his commitment to the power of written expression. To him, writing is not just a skill but a transformative tool that can shape perspectives and communicate profound feelings. For him, writing poems and articles isn\'t just a pastime; it\'s a profound way to explore the world through a different lens, unravel the beauty hidden in everyday moments, and share his unique perspective with others.',
		desc2: '',
		link: '',
	},
	{
		key: 'ashu',
		title: 'Ashu Tiwari',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Ashu Tiwari, a poetic soul entwined with the beauty of love and nature. Through verses that dance with passion, Ashu paints emotions on the canvas of the heart, weaving a tapestry where love and the natural world intertwine seamlessly. Join this wordsmith\'s journey, where every poem is a melody, echoing the symphony of love and the whispers of nature.',
		desc2: '',
		link: '',
	},
	{
		key: 'piyush',
		title: 'Piyush Gupta',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Piyush, a dedicated student of electrical engineering hailing from the vibrant city of Jaipur, Rajasthan, is known for his studious nature and vibrant personality. He is a poet who embraces life\'s contrasts. While often seen as the serious type, he too experiences bursts of emotions, much like everyone else. One mischievous day spent exploring hidden passages of nature with friends on his trusty bicycle inspired him to compose his poem, \'Traces Left Behind.\' With a unique blend of depth and playfulness, Piyush\'s poetry captures the essence of life\'s many dimensions, inviting readers to join him on his poetic journey.',
		desc2: '',
		link: '',
	},
	{
		key: 'aditya',
		title: 'Aditya Patil',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Aditya, hailing from Maharashtra pursuing civil engineering as a fresher, is a vivid dadydreamer and an all time night owl. Apart from binging movies all night, he loves to play cricket, scroll endlessly through instagram and hangout with friends. He also loves reading Myth fictions and is a huge fan of the Harry Potter novels. Poetry is his doorway to escape reality and jump into his own little world, as perfect as his imagination.',
		desc2: '',
		link: '',
	},
	{
		key: 'varun',
		title: 'Varun Khillare',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Varun Khillare, hails from Maharashtra, proud of his rich cultural heritage. He is currently pursuing his second year in electrical engineering. Looking at the night sky, observing the stars, and curious about the universe, in his free time, he cultivates the hobby of drawing emotions and silent observation of nature in poetry. He loves to play cricket and watch anime. He is a person who believes that the words are more dense and deep than black holes.',
		desc2: '',
		link: '',
	},
	{
		key: 'navaneeth',
		title: 'Navaneeth Sivadas',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Navaneeth is a chemical engineering fresher from Kerala. He loves watching movies and is a connoisseur of the thriller genre. He is also a fan of high-octane action films, such as that of the Mission-Impossible franchise. He also loves outdoor activities like football, and is eager to hang out with his friends. To develop creatively, he writes crime and horror short stories as a hobby.',
		desc2: '',
		link: '',
	},
	{
		key: 'arvind',
		title: 'Arvind Srinivasan',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Arvind is a rather private person who has long believed that explaining a miracle does not make it less of one. As a result, their interests have encompassed a wide range of real-world miracles, ranging from linguistics to quantum mechanics to computer science. You can often find them tracing the development of common miracles out of curiosity. Arvind also likes to play video games and read novels, often the obscure ones that catch their attention.',
		desc2: '',
		link: '',
	},
	{
		key: 'ritvik',
		title: 'Ritvik Ravi',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'My name\'s Ritvik, and I\'m a mechanical engineering freshman. Beyond academics and wasting time, I like reading scientific and financial literature. I also enjoy discussing opinions on controversial topics. You might\'ve even seen my around with my red headphones on!',
		desc2: '',
		link: '',
	},
	{
		key: 'chitraksh',
		title: 'Vasantati Chitraksh',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'While not being a nerd and trying to be a nerd, Chitraksh does everything he can to score, not only in exams but even in football matches. Crafting study plans and organizing tasks are part of his routine, but like everyone else, he sometimes falls short; nevertheless, he takes action, unlike many. He immerses himself in fictional philosophy and business autobiographies, and his quest for variety extends to watching rom-coms, action, and adventure movies.  The list is limited as he holds a lot of PORs and involvement in clubs and fitness activities. Clubs extend beyond Aranya and E-cell, they include Barca; he is a hardcore curler!!',
		desc2: '',
		link: '',
	},
	{
		key: 'sutar',
		title: 'Pranav Sutar',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Pranav is a fourth year B.Tech undergrad pursuing Computer Science Engineering. When he is not in CC Lab, you will find him in his room experimenting with different AI models and tools. One will find Pranav, a calm and pacifying person to talk to. Apart from claiming himself to be an innocent little kid, he finds himself being a Sanskrit Professor at Harvard if he wasn\'t into engineering.',
		desc2: '',
		link: '',
	},
	{
		key: 'vineela',
		title: 'Vineela Manchikatla',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'I am a computer science III year Btech student. writing stories as a hobby. I have already authored a book named Bhalpaw to Kadhal which was reviewed by Udaan. I also won a writing competition in scribbles club on historical fiction in telugu category. i am a film buff and like to write stories of variety of genres.',
		desc2: '',
		link: '',
	},
	{
		key: 'chandini',
		title: 'Chandini',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'This is chandini, from 4th year - Chemical Engineering and to say about, I am currently enjoying my free time out of all the responsibilities ive carried before in college.. Nevertheless, I couldn\'t leave the things completely if I get connected to them once. And that\'s how I still appear in some of the activities and events. And of course, I do love volunteering a few events out here and there. I am an occasional talker among not-so-known people but a loudspeaker among the known ones.',
		desc2: '',
		link: '',
	},
	{
		key: 'gopi',
		title: 'Gopi Krishna',
		tagLine1: '',
		tagLine2: '',
		role: '',
		year: '',
		desc1: 'Hello, I am Gopi Krishna from 4th year B.tech, Chemical Engineering. You might see me either always talking in a phone call in others phones than mine mostly. (bcz my phone will never have decent charge).In between handling my academics, and the "Academics", higher education club, I also juggle here and there searching for more work..Nevertheless, I a pure core guy..who never misses out my academics in looking out my other responsibilities .Iam also interested n talented in chess, cooking, coordinating events etc..',
		desc2: '',
		link: '',
	},
];
